version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

      # inject env file for build stage
      - echo "VITE_USER_POOL_ID=$VITE_USER_POOL_ID" > .env
      - echo "VITE_CLIENT_ID=$VITE_CLIENT_ID" >> .env

      # Use 7 characters of commit hash as image tags
#      - IMAGE_TAG=${COMMIT_HASH}
#      - REPO_URL=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
  build:
    commands:
      - docker build -t $REPO_URL:latest .
      - docker tag $REPO_URL:latest $REPO_URL:$IMAGE_TAG
  post_build:
    commands:
      - docker push $REPO_URL:$IMAGE_TAG
      - docker push $REPO_URL:latest
#      - echo "$SSH_KEY" > ~/.ssh/id_rsa
#      - chmod 400 ~/.ssh/id_rsa
#      - ssh -o StrictHostKeyChecking=no ubuntu@$INSTANCE "/home/ubuntu/app/deploy.sh $IMAGE_TAG"


artifacts:
  files:
    - Dockerrun.aws.json